### ISSUE TITLE
Update Website

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/clojurebridge-berlin.github.io#24]
Updates:
- [x] Add Ben to team twitter list and other team members.
- [x] Add Link to ClojureDojo Slack
- [x] Add section with other open tech initiatives _for women_ in Berlin (RailsGirls, NodeSchool, Open Tech School, women who code)

**Comment by vsmart** [comment]
I would keep the invitations to our slack on a per-person only basis, and not share a public link.
But +1 to adding the other tech initiatives. :)

**Comment by Malwine** [comment]
@vsmart we could put a link to a form where you request an invite. because some people dont know how to get a personal invite maybe... will ecplain this to you later :)

**Comment by Malwine** [comment]
Closing for now
