### ISSUE TITLE
A page for the learners group

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/clojurebridge-berlin.github.io#28]
Throughout the year when no workshops are offered people should have the possibility to get informed about the learners group, which they can join at any time.

We want a page that describes in a few words what the learners group is and what people do there. Moreover, it should describe who can join. We could add some cute pictures from Julias presentation.

Below all of that there should be a way to contact us (because the location changes frequently and also we want to keep it a safe space).

**Comment by ioctaptceb** [comment]
Some comments from the other issue:

mentioned by @plexus 
Main points that should be on such a page (someone correct me if I'm wrong or misrepresenting things)
- meets three times per month on Wednesday, the fourth Wednesday everyone goes to the Clojure Meetup
- beginners are most welcome. If you've done the workshop you know more than enough (this seems to be a misconception and a reason why not many people find the way: they think you need to be somewhat "advanced")
- you can either work on your own stuff, or find people with shared interests to work on a project together over a longer time
- we do both artsy stuff and "practical" (i.e. webdev) stuff
- the evening starts with a vegan potluck, so feel free to bring and share some food
- there will be coaches to help you
- location can vary so best to get in touch
- main communication channel is slack, if you've done the workshop and want to join the group then you can get an invite
- there's a tumblr with some stuff the art group did. It's not very up to date but I would still link to it.

mentioned by @vsmart 
Typical schedule:
7pm - 8pm: Vegan potluck & hanging out
8pm - 10pm(ish) Clojure Hacking

**Comment by Malwine** [comment]
Please remember to have the site content in English and German. Thank you 😊

**Comment by vsmart** [comment]
closed in https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/issues/39
