### ISSUE TITLE
⚠️Usage hint for our website pictures ⚠️

### ISSUE THREAD

**Issue by Malwine** [clojurebridge-berlin/clojurebridge-berlin.github.io#29]
:warning:
We need to put a hint on the website if and how people (other chapters, press etc.) are allowed to use our pictures and how.

**Comment by vsmart** [comment]
@Malwine Can you think of an example of what this would look like somewhere? perhaps even a custom text?

**Comment by Malwine** [comment]
The text would go somewhere at the bottom. I would like a hint for future forks and press. 
**Below:** `ClojureBridge Berlin is a chapter of clojurebridge.org.`
E.g.:

> You can fork this website for your ClojureBrdidge chapter at [link]. 
> Please do not use our pictures as they are only meant for ClojureBridge Berlin Chapter. 
> If you want to use any of our pictures for web or press please contact us at [mail].

**Comment by Malwine** [comment]
@vsmart Also it would be good to have the text again in our Readme 😉
