### ISSUE TITLE
Make sponsor tiers more clear 

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/clojurebridge-berlin.github.io#30]
As mentioned in [this issue](https://github.com/clojurebridge-berlin/organization/issues/103) I'd like to list out more clearly: 
- price for each tier
- what we use the money for
- benefits for each tier 

in each section, rather than as a paragraph below. 

for example : 

```
 Gold tier (1000 Eur)
 * Your money pays for workshop food. :pizza:
 * You get to support diversity in Clj community
 * You get: Social media shout outs, website listing, to display swag.
```

**Comment by Malwine** [comment]
Maybe we can get some inspiration from http://euroclojure.org/sponsorship
![screen shot 2016-10-03 at 22 14 03](https://cloud.githubusercontent.com/assets/5123681/19052349/b7449ed8-89b6-11e6-9a8e-7f3096fca165.png)

**Comment by vsmart** [comment]
Done in https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/issues/31
