### ISSUE TITLE
add code of conduct notice to coaches training

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/clojurebridge-berlin.github.io#42]
Code of Conduct isn't mentioned in the slides. It should be mentioned right at the start (since it also applies to the training evening) and perhaps again later in more detail, like "how do I react if an attendee complains about CoC violation?" (answer: send them to us/orga)

**Comment by daveliepmann** [comment]
Convenience links:

https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/blob/master/coaches_training.deck.html

and

http://clojurebridge-berlin.org/coaches_training.deck.html

**Comment by daveliepmann** [comment]
Forget that commit; see https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/compare/add-coc-to-coach-training instead

**Comment by daveliepmann** [comment]
See #65 and #66.
