### ISSUE TITLE
update learner's group page with co_up info

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/clojurebridge-berlin.github.io#48]
We have a new location for the learners group -- at co_up! :tada: 

We should edit the learners group page to include: 

* a link to their CoC http://co-up.de/code-of-conduct.html
* a link to their location info (with accessibility info etc) http://co-up.de/space-instructions.html

**Comment by lislis** [comment]
Started a PR here https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/56

**Comment by vsmart** [comment]
merged in #56
