### ISSUE TITLE
Improve grammar of English workshop description

### ISSUE THREAD

**Issue by daveliepmann** [clojurebridge-berlin/clojurebridge-berlin.github.io#51]
On clojurebridge-berlin.org under **Workshop** it says:

>**English**: ClojureBridge aims to increase diversity within the Clojure community by offering free, beginner-friendly Clojure programming workshops for people who identify as **woman or non-binary**.

I think "identify as woman" is clunky and ungrammatical. (I think it was introduced accidentally in 21d87dcde49d48081183780eabfa4de5d4c325ed while improving phrasing for non-binary folks.) Maybe we want to say "...workshops for people who identify as a woman or as non-binary"?

**Comment by vsmart** [comment]
@daveliepmann "ClojureBridge is a free Clojure programming workshop for women and non-binary people" this is the official tagline, it should be changed to that. :) Good catch!

**Comment by daveliepmann** [comment]
PR incoming

**Comment by daveliepmann** [comment]
See #52
