### ISSUE TITLE
Add T-shirt sponsorship for sponsorpage

### ISSUE THREAD

**Issue by lislis** [clojurebridge-berlin/clojurebridge-berlin.github.io#53]
The idea is to have one single sponsorship package that pays for t-shirts.
I think the last estimate was around 1500 Euro.

The perk: the company's name (maybe logo) on the t-shirt.

This way we can allocate money specifically for having t-shirts and don't have to juggle with budgets.
If we find a t-shirt sponsor we'll make shirts, if not then not. Wdyt?

**Comment by vsmart** [comment]
Merged in https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/55 \o/
