### ISSUE TITLE
Update list of team members

### ISSUE THREAD

**Issue by daveliepmann** [clojurebridge-berlin/clojurebridge-berlin.github.io#57]
It would be nice to have a more current Team description, while still giving credit to alumni.

>The Team:
>Arne, Ben, Bettina, Franziska, Jelle, Julia, Lisa, Malwine, Martin & Nicola.

**Comment by vsmart** [comment]
@daveliepmann do you want to propose a list? :innocent:

**Comment by daveliepmann** [comment]
Well the current team includes, but is not limited to, Franka, Lisa, Dani, Ben, Dave, David, Saskia, Chris, Nils, Tibor, Johanna, Julchen, and I'm forgetting two people from the last few meetings.

Do we prefer "alumni", or something like "orga team" including everybody, and "organizers for the next event" including just currently active folks?

**Comment by daiyi** [comment]
I propose a team photo at the next orga meeting!

**Comment by daiyi** [comment]
Here's a wiki page to collect information: https://github.com/clojurebridge-berlin/organization/wiki/Orga-Team-History
