### ISSUE TITLE
consider alternative phrasings to avoid using "women" as an adjective

### ISSUE THREAD

**Issue by davidchambers** [clojurebridge-berlin/clojurebridge-berlin.github.io#59]
> We are especially looking for women coaches this summer.

I find it jarring to read _women_ (a noun) used as an adjective (mentally replace _women_ with _men_ in the sentence as a test). I suggest we make one of these changes:

> We are especially looking for <del>women</del> <ins>female</ins> coaches this summer.

> We are especially looking for women <ins>to be</ins> coaches this summer.

**Comment by daveliepmann** [comment]
> We are especially looking for women to be coaches this summer.

This reads way better to me than "female coaches".

**Comment by vsmart** [comment]
pls change to `We are especially looking for women and non-binary people to be coaches this summer!` 

thanks for pointing this out @davidchambers \o/
