### ISSUE TITLE
Coaches training slides have outdated # of workshops

### ISSUE THREAD

**Issue by daveliepmann** [clojurebridge-berlin/clojurebridge-berlin.github.io#62]
>[So far two workshops in Berlin: July 2015, January 2016, and now the third one coming up! 🎉](http://clojurebridge-berlin.org/coaches_training.deck.html#whats_a_clojurebridge)

🤖 says: `FALSCH`

**Comment by daveliepmann** [comment]
...we had three, and we're planning the fourth for fall 2017, right? Or am I crazy?

**Comment by plexus** [comment]
You are correct. The third one was 25/26 November 2016.

**Comment by vsmart** [comment]
Actually we've had four workshops and are planning the 5th :) 3 in 2016 (Jan, June, November), and one in Summer of 2015.

**Comment by plexus** [comment]
🤐 😊
