### ISSUE TITLE
Add nextjournal logo to sponsors list

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/clojurebridge-berlin.github.io#88]
We are missing nextjournal in our sponsors list.

This is a small change to index.html, similar to this PR #86 

Waiting to hear back from them to provide us with a logo file.
cc @saskali

**Comment by lislis** [comment]
I took the svg from their website https://github.com/clojurebridge-berlin/clojurebridge-berlin.github.io/pull/89
