### ISSUE TITLE
Expand on learning resources

### ISSUE THREAD

**Issue by martinklepsch** [clojurebridge-berlin/clojurebridge-berlin.github.io#9]
It would be nice if we collect more learning resources and catalog/link them on our website,
- https://aphyr.com/posts/301-clojure-from-the-ground-up-welcome

**Comment by nynnejc** [comment]
http://www.4clojure.com/

**Comment by Malwine** [comment]
I guess http://www.braveclojure.com/introduction/ is also an option.
We can add these links to the material section.

**Comment by Malwine** [comment]
We may not need to duplicate the links in both languages.

**Comment by Malwine** [comment]
The links above are resolved in the new material section. Pleas open a new issue for more links.
